services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
volumes:
  qdrant_storage:
