services:
  n8n_web:
    container_name: n8n_web
    image: n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  n8n_worker:
    container_name: n8n_worker
    image: n8nio/n8n:latest
    command: worker
    restart: always
    ports:
      - 5677:5678
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    environment:
      - EXECUTIONS_PROCESS=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
    depends_on:
      - n8n_web
      - redis
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  n8n_data:
  postgres_data: