services:
  icinga2:
    container_name: icinga2
    hostname: icinga2
    image: jordan/icinga2:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/icinga/cache:/var/cache/icinga2
      - ./data/icinga/certs:/etc/apache2/ssl
      - ./data/icinga/etc/icinga2:/etc/icinga2
      - ./data/icinga/etc/icingaweb2:/etc/icingaweb2
      - ./data/icinga/lib/icinga:/var/lib/icinga2
      - ./data/icinga/lib/php/sessions:/var/lib/php/sessions
      - ./data/icinga/log/apache2:/var/log/apache2
      - ./data/icinga/log/icinga2:/var/log/icinga2
      - ./data/icinga/log/icingaweb2:/var/log/icingaweb2
      - ./data/icinga/log/mysql:/var/log/mysql
      - ./data/icinga/spool:/var/spool/icinga2
      - ./data/icinga/cron.d/icinga:/etc/cron.d/icinga
    ports:
      - 80:80
      - 443:443
      - 5665:5665
  
  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    restart: always
    hostname: graphite
    env_file:
      - .env
    volumes:
      - ./data/graphite/conf:/opt/graphite/conf
      - ./data/graphite/storage:/opt/graphite/storage
      - ./data/graphite/log/graphite:/var/log/graphite
      - ./data/graphite/log/carbon:/var/log/carbon
  
  mysql:
    container_name: mysql
    hostname: mysql
    image: mariadb:10.3
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql/data:/var/lib/mysql